export const UPLOAD_IMAGES_REQUEST = 'UPLOAD_AVATAR_REQUEST'
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'
export const UPLOAD_IMAGES_FAILURE = 'UPLOAD_AVATAR_FAILURE'

export const GET_SCORE = 'GET_SCORE'
